### ISSUE TITLE
Matplotlib scales with unyt_quantity

### ISSUE THREAD

**Issue by vdbma** [yt-project/unyt#384] opened 2023-03-07 15:02 UTC
* unyt version: 2.9.5 (installed with pip)
* matplotlib version: 3.7.1 (installed with pip)
* Python version: 3.9.9
* Operating System: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1

### Description
Using the `linthresh` or `linear_width` matplotlib scales options (respectively with `symlog` and `asinh`) with a `unyt_quantity` raises `UnitOperationError`.

### What I Did

Minimal example (each ax  independently  raises the error).
```python
import numpy as np
import matplotlib.pyplot as plt
from unyt import g,matplotlib_support
# Prepare sample values for variations on y=x graph:
x = np.linspace(-10, 10, 500)*g

with matplotlib_support:
    fig1 = plt.figure()
    ax0, ax1  = fig1.subplots(1, 2, sharex=True)

    ax0.plot(x, x)
    ax0.set_yscale('symlog',linthresh=np.abs(x).min()*30)
    ax0.grid()
    ax0.set_title('symlog')

    ax1.plot(x, x)
    ax1.set_yscale('asinh',linear_width=np.abs(x).min()*30)
    ax1.grid()
    ax1.set_title('asinh')
```

Crash log :

```python-traceback
Traceback (most recent call last):
  File "/***/pythondivers/asinh_unyt/main.py", line 16, in <module>
    ax1.plot(x, x)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1688, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 499, in _plot_args
    self.axes.xaxis.update_units(x)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 1680, in update_units
    self._update_axisinfo()
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 1716, in _update_axisinfo
    self.set_default_intervals()
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 2466, in set_default_intervals
    not self.axes.viewLim.mutatedx()):
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 857, in viewLim
    self._unstale_viewLim()
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 852, in _unstale_viewLim
    self.autoscale_view(**{f"scale{name}": scale
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2930, in autoscale_view
    handle_single_axis(
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2927, in handle_single_axis
    set_bound(x0, x1)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3530, in set_xbound
    self.set_xlim(sorted((lower, upper),
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3650, in set_xlim
    return self.xaxis._set_lim(left, right, emit=emit, auto=auto)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 1229, in _set_lim
    other._axis_map[name]._set_lim(
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 1217, in _set_lim
    self.set_view_interval(v0, v1, ignore=True)
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axis.py", line 2211, in setter
    setattr(getattr(self.axes, lim_name), attr_name, (vmin, vmax))
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 857, in viewLim
    self._unstale_viewLim()
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 852, in _unstale_viewLim
    self.autoscale_view(**{f"scale{name}": scale
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2933, in autoscale_view
    handle_single_axis(
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2917, in handle_single_axis
    x0, x1 = inverse_trans.transform([x0t - delta, x1t + delta])
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/transforms.py", line 1490, in transform
    res = self.transform_affine(self.transform_non_affine(values))
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/matplotlib/scale.py", line 400, in transform_non_affine
    abs_a / self.linthresh - self._linscale_adj))
  File "/***/.pyenv/versions/unyt_asinh/lib/python3.9/site-packages/unyt/array.py", line 1892, in __array_ufunc__
    raise UnitOperationError(ufunc, u0, u1)
unyt.exceptions.UnitOperationError: The <ufunc 'subtract'> operator for unyt_arrays with units "1/g" (dimensions "1/(mass)") and "dimensionless" (dimensions "1") is not well defined.
```

### Comment

Using `np.abs(x.value).min()*30` instead of `np.abs(x).min()*30` fixes this, but then `matplotlib_support` becomes a bit pointless.

Is this behaviour expected ?

**Comment by ngoldbaum** [comment] 2023-03-07 15:18
I doubt there’s much unyt can do about this (unless we’re incorrectly using matplotlib’s unit support somehow). I’d report this to matplotlib.

**Comment by neutrinoceros** [comment] 2023-03-08 09:43
it seems that the same issue arises when using `astropy.units` instead of `unyt`, so I tend to agree that it's probably an upstream issue. I'll file a report to matplotlib when I have time to check if there's anything we've missed.

**Comment by neutrinoceros** [comment] 2023-04-02 16:04
I went back and forth on this.
Here's a reproducer as a test file for both `unyt` and `astropy.units`
```python
import numpy as np
import matplotlib.pyplot as plt

import unyt as un
from astropy import units as astro_un

import pytest


@pytest.mark.parametrize("linscale", [1, 1*un.g])
def test_unyt(linscale):
    x = np.linspace(-1, 1, 10)*un.g

    with un.matplotlib_support:
        fig, ax = plt.subplots()
        ax.plot(x, x)
        ax.set_yscale('symlog', linthresh=np.abs(x).min(), linscale=linscale)
        fig.savefig("/tmp/test_unyt.png")

@pytest.mark.parametrize("linscale", [1, 1*astro_un.g])
def test_astropy(linscale):
    x =  np.linspace(-1, 1, 10)*astro_un.g

    fig, ax = plt.subplots()

    ax.plot(x, x)
    ax.set_yscale('symlog', linthresh=np.abs(x).min(), linscale=linscale)
    fig.savefig("/tmp/test_astropy.png")
```

all four tests crash because some invalid operation always criples in (either log() operators or basic addition/subtraction between dimensionless numbers and unitful ones). From what I can grasp, it seems that putting the responsibility of validating/sanitizing such inputs on matplotlib would add a significant amount of complexity there, and it's not even obvious that we can agree on a solution that fits both `unyt` and `astropy.units` (let alone any other library I wouldn't know about).

ATM I don't think it is worth pushing over to MPL folks, and as unsatisfactory as it may be, I think I'll just close this as "won't fix" (at least for now). If anyone feels otherwise feel free to use the above tests in your report.

**Closed by neutrinoceros** 2023-04-02 16:04 UTC
