### ISSUE TITLE
Unexpected behaviour when selecting elements

### ISSUE THREAD

**Issue by MatthieuSchaller** [yt-project/unyt#374] opened 2023-02-22 21:23 UTC
* unyt version: 2.9.4
* Python version: 3.10.6 
* Operating System: irrelevant

### Description

This is related to #373. 
There is some unexpected behaviour when using the simple numpy masking rules with dimensionful arrays:

```python
In [1]: import unyt

In [2]: unyt.__version__
Out[2]: 'v2.9.4'

In [3]: import numpy as np

In [4]: x = unyt.unyt_array(10**(5 * np.random.rand(10) - 2.5), "1 / Gyr")

In [5]: x < 0.01
Out[5]: 
array([False, False, False, False, False, False, False, False,  True,
       False])
```

The instruction on line 5 is ambiguous as not units are provided on the RHS of <. 
This can get even more tortuous if `x` gets transformed into other units on the way. 
A much safer behaviour explicitly demanding a `unyt_quantity` on the RHS would likely be good to prevent dangerous user code downstream.

**Comment by ngoldbaum** [comment] 2023-02-22 21:44
I made an explicit choice to allow this. I find needing to add units to do the comparison with a scalar to be obnoxious, particularly when working interactively.

**Comment by ngoldbaum** [comment] 2023-02-22 21:44
I believe you will get an error if you try to compare with a quantity that has dimensionally incorrect units.

**Comment by ngoldbaum** [comment] 2023-02-23 16:27
Closing since this is the intended behavior, I checked and you do get an error if you compare with a quantity that has dimensionally incorrect units, and it does the proper unit conversion for dimensionally correct units.

**Closed by ngoldbaum** 2023-02-23 16:27 UTC
