### ISSUE TITLE
Is it possible to get Hz * s to reduce?

### ISSUE THREAD

**Issue by dangom** [yt-project/unyt#49] opened 2018-08-15 19:53 UTC
* unyt version: 1.0.6
* Python version: 3.6.6
* Operating System: MacOS 10.13.6

### Description

I multiplied Hz and seconds and got a Hz * s quantity.
I expected a result without dimension, as in Km / Km.

### What I Did

```
In [281]: (1*u.Hz) * (1*u.s)
Out[281]: unyt_quantity(1.0, 'Hz*s')

In [282]: (1*u.km) / (1*u.km)
Out[282]: unyt_quantity(1.0, '(dimensionless)')

In [286]: ((1*u.Hz) * (1*u.s)).to(u.dimensionless)
Out[286]: unyt_quantity(1.0, '(dimensionless)')
```

**Comment by ngoldbaum** [comment] 2018-08-15 20:07
Ah, this is happening because multiplication and division for unit objects isn't going through the unit system. I think this will be a straightforward change...

**Comment by ngoldbaum** [comment] 2018-08-15 20:08
And good catch! I think I noticed something similar when going through my talk for unyt at scipy but hadn't come back to reproduce and debug.

**Comment by ngoldbaum** [comment] 2019-01-22 19:58
I opened https://github.com/yt-project/unyt/pull/58 which will fix this when it's merged. It ended up being a bigger change than I anticipated back in August.

**Closed** 2019-01-23 18:54 UTC
