### ISSUE TITLE
Optimize importing unyt

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/unyt#27] opened 2018-07-13 14:33 UTC
As reported by @majj, importing unyt takes about one second. I suspect there isn't much we can do about this since we need to import both numpy and sympy.

**Comment by neutrinoceros** [comment] 2021-02-08 22:23
I've been digging into this since the problem has apparently gotten worse.
Here's a graphical profile for `import unyt` (as from the latest master branch)

![Screen Shot 2021-02-08 at 22 55 44](https://user-images.githubusercontent.com/14075922/107286400-d81b3b00-6a60-11eb-86fa-0c6b423c00f4.png)

for reproduction:

```bash
$ python -X importtime import_unyt.py 2> import_unyt.log
$ tuna import_unyt.log
```
with
```python
# import_unyt.py
import unyt
```
and using https://github.com/nschloe/tuna

So indeed, numpy and sympy are taking about a second to import (~0.75s in this particular run), but about 40% (0.9s) of the import time is spent importing `unyt.physical_constants`.
I was able to narrow it down to this line:
https://github.com/yt-project/unyt/blob/aaa2b244207c14c5f472214595a00201d105c0ae/unyt/unit_systems.py#L98
- since no exception is actually caught in this try block when importing unyt, I tried removing the try block and keeping the call, which did not lead to any change I could measure with this (admittedly not very robust) profiling method
- removing the call to `Unit.in_base()` altogether leads to an important gain however reduces the total import time by 0.8s (~35%) so there's room for optimisation here I think.
I may report back if I can grasp a better idea of how to improve on this :)

**Comment by neutrinoceros** [comment] 2021-05-01 21:15
update: we can track it much more closely with
```
python -m cProfile -o log.pstats import_unyt.py
gprof2dot --colour-nodes-by-selftime log.pstats | dot -Tsvg -o out.svg
```
Where the most time-consuming island looks like this:
![Screenshot 2021-05-01 at 23 13 15](https://user-images.githubusercontent.com/14075922/116795112-df3b6d80-aad2-11eb-999d-5f3f55a79087.png)

so it seems that 928533 deepcopies are performed at import time, which can very likely be optimised.

**Comment by mattwthompson** [comment] 2021-07-29 21:42
`unyt.physical_constants` does seems to be the culprit for some incredibly slow import times I'm coming across (`python -X importtime -c "import unyt" 2> tuna.log && tuna tuna.log`)


![image](https://user-images.githubusercontent.com/7935382/127569547-3798de5e-d0c1-479e-85ae-fc8d0792e56a.png)

**Comment by neutrinoceros** [comment] 2022-07-16 08:13
This seems to not be the case anymore with unyt 2.9.0, now sympy is the most important offender (takes between 25 and 40% of unyt's import time on my machine), so there's actually not much room left to optimise unyt's import time in unyt itself.
One minor optimisation that (I think) is still doable would be to delay importing matplotlib even when it's available. I will experiment with this idea and possibly propose we close this ticket.

**Comment by neutrinoceros** [comment] 2022-07-16 09:35
With #250 and #251 I think we should be able to close this

**Comment by neutrinoceros** [comment] 2022-07-19 08:46
For details here's the state of things when combining the above optimisations
![Screenshot 2022-07-19 at 10 39 15](https://user-images.githubusercontent.com/14075922/179706798-02c01b27-54e5-4adf-9625-47f6d689be2a.png)

Here, sympy + numpy represent at least 50 to 60% of unyt's import time. Maybe there are still ways to reduce the remaining overhead, but it's hard to even profile correctly: Tuna doesn't display much detail for `unit_symbols.py` because not everything makes it into the profile data (by CPython's design), but I *think* that there is also a large fraction of it due to sympy.

**Comment by neutrinoceros** [comment] 2022-07-19 21:23
Found another simple optimisation, this time requiring a discussion upstream https://github.com/sympy/sympy/pull/23804

**Closed** 2022-09-15 11:51 UTC
